#!/usr/bin/env bash
# Generate a scout-module directory with facet-separated flake.nix (+ optional settings.nix, dummy flake.lock).
# Usage: new-module.sh <modules-dir> <name> [facet...]
# Facets: scout | home | baseline | flakelet  (any subset; all four sections always present in flake.nix)
set -euo pipefail

MODULES_DIR="${1:?modules directory required}"
NAME="${2:?module name required}"
shift 2

# shellcheck source=./scout-lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/scout-lib.sh"

want_scout=false
want_home=false
want_baseline=false
want_flakelet=false
for facet in "$@"; do
  case "$facet" in
    scout) want_scout=true ;;
    home) want_home=true ;;
    baseline) want_baseline=true ;;
    flakelet) want_flakelet=true ;;
    profile)
      echo "nix-scout new: use facet name 'scout' (not 'profile')" >&2
      exit 1
      ;;
    home-files|homefiles)
      echo "nix-scout new: use facet name 'home' (not 'home-files')" >&2
      exit 1
      ;;
    *)
      echo "nix-scout new: unknown facet '$facet' (supported: scout home baseline flakelet)" >&2
      exit 1
      ;;
  esac
done

if [[ ! "$NAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9_-]*$ ]]; then
  echo "nix-scout new: invalid module name '$NAME' (want [a-zA-Z0-9][a-zA-Z0-9_-]*)" >&2
  exit 1
fi

if [[ ! -d "$MODULES_DIR" ]]; then
  echo "nix-scout new: modules directory missing: $MODULES_DIR" >&2
  exit 1
fi

mod_dir="$MODULES_DIR/$NAME"
if [[ -e "$mod_dir" ]]; then
  echo "nix-scout new: refusing to overwrite existing path: $mod_dir" >&2
  exit 1
fi

mkdir -p "$mod_dir"

# --- flake.nix ----------------------------------------------------------------
{
  printf '%s\n' "{"
  printf '%s\n' "  # ${NAME} — scout module (generated by nix-scout new)."
  printf '%s\n' "  # \`inputs ? nix-scout\` gates scout/home: true under nix-scout eval/switch,"
  printf '%s\n' "  # false under flakelet path eval — facets stay definitionally exclusive."
  printf '%s\n' ""
  printf '%s\n' "  inputs.nixpkgs.url = \"github:NixOS/nixpkgs/nixos-26.05\";"
  printf '%s\n' "  inputs.nix-scout.url = \"github:mikenrafter/nix-scout\";"
  printf '%s\n' "  inputs.nix-scout.inputs.nixpkgs.follows = \"nixpkgs\";"
  printf '%s\n' ""
  printf '%s\n' "  outputs = { nixpkgs, ... }@inputs:"
  printf '%s\n' "  let"
  printf '%s\n' "    system = \"x86_64-linux\";"
  printf '%s\n' "    lib = nixpkgs.lib;"
  printf '%s\n' "  in"
  printf '%s\n' "  lib.optionalAttrs (inputs ? nix-scout) ("
  printf '%s\n' "    let"
  printf '%s\n' "      pkgs = import nixpkgs { inherit system; };"
  printf '%s\n' "    in {"

  printf '%s\n' "      # scout"
  if [[ "$want_scout" == "true" && "$want_home" == "true" ]]; then
    printf '%s\n' "      # home"
    cat <<EOF
      packages.\${system}.scout = pkgs.symlinkJoin {
        name = "scout-${NAME}";
        paths = [
          (pkgs.writeShellScriptBin "${NAME}" ''
            echo "${NAME}: replace this scout stub"
          '')
          (pkgs.runCommand "scout-${NAME}-home" { } ''
            mkdir -p \$out/home-files/.config/${NAME}
            echo '{}' > \$out/home-files/.config/${NAME}/config.json
          '')
        ];
      };
EOF
  elif [[ "$want_scout" == "true" ]]; then
    cat <<EOF
      packages.\${system}.scout = pkgs.buildEnv {
        name = "scout-${NAME}";
        paths = [
          (pkgs.writeShellScriptBin "${NAME}" ''
            echo "${NAME}: replace this scout stub"
          '')
        ];
        pathsToLink = [ "/bin" ];
      };
EOF
    printf '%s\n' "      # home"
  elif [[ "$want_home" == "true" ]]; then
    printf '%s\n' "      # home"
    cat <<EOF
      packages.\${system}.scout = pkgs.runCommand "scout-${NAME}-home" { } ''
        mkdir -p \$out/home-files/.config/${NAME}
        echo '{}' > \$out/home-files/.config/${NAME}/config.json
      '';
EOF
  else
    printf '%s\n' "      # home"
  fi

  printf '%s\n' "      # baseline"
  if [[ "$want_baseline" == "true" ]]; then
    cat <<EOF
      baseline = { lib, ... }: {
        # Add system-wide NixOS options here. Imported directly into the
        # host's module list at nixos-rebuild eval time — never applied by
        # \`nix-scout switch\`; only takes effect on the next rebuild.
      };
EOF
  fi

  printf '%s\n' "    }"
  printf '%s\n' "  ) // {"
  printf '%s\n' "    # flakelet"
  if [[ "$want_flakelet" == "true" ]]; then
    cat <<EOF
    flakelets.default =
      { types, ... }:
      {
        options = {
          # Add flakelet options here.
        };

        impl =
          { options, pkgs, name, ... }:
          {
            services.\${name} = {
              description = "${NAME}";
              after = [ "network.target" ];
              wantedBy = [ "multi-user.target" ];
              serviceConfig = {
                Type = "oneshot";
                RemainAfterExit = true;
                ExecStart = "\${pkgs.coreutils}/bin/true";
              };
            };
          };
      };
EOF
  fi
  printf '%s\n' "  };"
  printf '%s\n' "}"
} >"$mod_dir/flake.nix"

# --- settings.nix (flakelet registration) ------------------------------------
if [[ "$want_flakelet" == "true" ]]; then
  cat >"$mod_dir/settings.nix" <<EOF
{ config, lib, ... }: {
  enable = true;
  output = "flakelets.default";
  settings = { };
  autoUpdate = { enable = true; interval = "hourly"; };
}
EOF
fi

# --- dummy flake.lock (nixpkgs only; placeholder pins) -----------------------
write_sentinel_lock "$mod_dir/flake.lock"

echo "nix-scout: created $mod_dir"
echo "nix-scout: a full nixos-rebuild is required before any flakelet facet can be registered or switched"
